controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # acker_control:
    #   type: ackermann_steering_controller/AckermannSteeringController
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# acker_control:
#   ros__parameters:

#     publish_rate: 50.0

#     base_frame_id: base_link
#     reference_timeout: 2.0
#     open_loop: false
#     velocity_rolling_window_size: 10
#     # position_feedback: false
#     traction_joints_names: [rear_right_wheel_joint, rear_left_wheel_joint]
#     steering_joints_names: [front_right_steering_joint, front_left_steering_joint]

#     wheelbase: 0.145
#     traction_track_width: 0.133
#     traction_wheels_radius: 0.0184

#     use_stamped_vel: false

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['wheel_lf_Joint','wheel_lb_Joint']
    right_wheel_names: ['wheel_rf_Joint','wheel_rb_Joint']
    wheel_separation: 0.133
    wheel_radius: 0.0184
    wheel_separation_multiplier: 1.0